name: Issues

on:
  issues:
    types: [opened]
env:
  MY_SECRET: ${{ secrets.MY_SECRET }}
  
jobs:
  print_issue_title:
    runs-on: ubuntu-latest

    name: Print issue title
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with:
        # Number of commits to fetch. 0 indicates all history for all branches and tags.
        # Default: 1
        fetch-depth: '1'

    # Runs a single command using the runners shell
    - name: Git Log
      run: git log
      
    - run: echo "${{github.event.issue.title}}"

    